#!/bin/bash

# -- Configure these? -- #
files=/root /var/www/html /opt # What files to backup (Add multiple)
location=/root # Where to back them up to
day=$(date +%A+%T)
host=$(hostname -s)
file_name=${host}-${day}


# -- Colors -- #
RED='\033[0;31m'
CYAN='\033[0;36m'
LG='\033[0;37m'
NO='\033[0m'
GR='\033[1;32m'
BYELLO="\033[1;33m"
UYellow="\033[4;33m" 

echo "
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+

          Crontab & rsync backup script
	            Version: v1.0 

+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
"

while true; do
    read -p "Do you want to backup your files? [Y/n] " answer2
    case $answer2 in
        [Yy]* ) tar -czf ${location}/${file_name}.tgz ${files} ; break;;
        [Nn]* ) echo "${LG}[${RED}!${LG}] ${RED}Exiting${NO}"; break;;
        * ) echo "${LG}[${RED}!${LG}] ${RED}Invalid Arguments.${NO}";;
    esac
done
sleep 2
