#!/bin/bash

# -- Colors -- #
RED='\033[0;31m'
CYAN='\033[0;36m'
LG='\033[0;37m'
NO='\033[0m'
GR='\033[1;32m'
BYELLO="\033[1;33m"
UYellow="\033[4;33m" 

SSH_PORT=$ssh_port
ssh_port=`grep ^Port /etc/ssh/sshd_config | awk '{print $2}'`
IP=`wget -q -O - http://icanhazip.com/ | tail`

echo "
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+

          Bash Port Changer
            Version: v1.1 

+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
"
echo "
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+

 "${LG}[${RED}!${LG}] ${UYellow}Server Infomation${NO} ${LG}[${RED}!${LG}]${NO}"

 "${RED}Listening on...${NO} [${GR}$ssh_port${NO}]"
 "${RED}Current IP.....${NO} [${GR}$IP${NO}]"
 
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+

 "${LG}[${RED}!${LG}] ${UYellow}Server Security Info${NO} ${LG}[${RED}!${LG}]${NO}"
 
 "${LG}[${RED}LastLog${LG}]" `lastlog | grep root`
 
 "${LG}[${RED}Checking${LG}] Auth.log [ ${RED}Last 5 Lines${NO} ]"
 `sleep 2`
 `cat /var/log/auth.log >> logs.txt && tail -5 /var/log/auth.log`
 
+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+
"

if [ -e "/etc/ssh/sshd_config" ];then
  [ -z "`grep ^Port /etc/ssh/sshd_config`" ] && ssh_port=22
  
while :; do echo
  read -p "Insert new port: " SSH_PORT
  [ -z "$SSH_PORT" ]
if [ $SSH_PORT -eq 22 >/dev/null 2>&1 -o $SSH_PORT -gt 1024 >/dev/null 2>&1 -a $SSH_PORT -lt 65535 >/dev/null 2>&1 ];then
break
else
echo "${LG}[${RED}!${LG}] ${RED}Incorrect usage. Between 22, 1054 & 65530?${NO} ${LG}[${RED}!${LG}]${NO}\n"
fi
done
 
if [ -z "`grep ^Port /etc/ssh/sshd_config`" -a "$SSH_PORT" != '22' ];then
sed -i "s@^#Port.*@&\nPort $SSH_PORT@" /etc/ssh/sshd_config
elif [ -n "`grep ^Port /etc/ssh/sshd_config`" ];then
sed -i "s@^Port.*@Port $SSH_PORT@" /etc/ssh/sshd_config
fi
fi
